# Zadanie 1
Napisz funkcję, która sprawdzi czy w podanej macierzy występuję zadana wartość.

In [26]:
import numpy as np

def f1(m,n):
    if np.any(m==n):
        return "Podana wartość występuje w macierzy"
    else:
        return "Podana wartość nie występuje w macierzy"
f1(np.array([[1,2],[3,4]]),2)    

'Podana wartość występuje w macierzy'

# Zadanie 2
Napisz funkcję, która zwróci średnią geometryczną wektora liczb (liczby sa dodatnie).

In [11]:
def geometric_mean(w):
    x=np.prod(w)
    x**=1/w.size
    return x
geometric_mean(np.array([1,2,3,4]))

2.213363839400643

# Zadanie 3
Napisz funkcję, która dla zadanych wektórów obliczy ich iloczyn skalarny.

In [13]:
def scalar_product(x,y):
    return np.dot(x,y)
scalar_product(np.array([1,2]),np.array([3,4]))

11

# Zadanie 4
Napisz funkcję, która wygeneruje macierz o zadanych rozmiarach z tą sama wartością liczbową ale bez użycia metody np.full().

In [17]:
def full(x,n,n2):
    return np.array([[x for i in range(n)]for j in range(n2)])
full(2,10,15)

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

# Zadanie 5
Napisz funkcję, która wygeneruje macierz kwadratową określonego rozmiaru n o zerach na przekątnej i jedynkach na pozostałych pozycjach.

In [20]:
def fill(n):
    matrix=np.array([[0 for i in range(n)]for j in range(n)])
    np.fill_diagonal(matrix,1)
    return matrix
fill(5)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Zadanie 6
Napisz funkcję, która zamieni wszystkie ujemne wartości w macierzy na 0.

In [33]:
def positive(m):
    for i,j in np.ndenumerate(m):
        if j<0:
            m[i]=0
    return m        
        
positive(np.array([[1,-3],[-5,9]]))        

array([[1, 0],
       [0, 9]])

# Zadanie 7
Napisz funkcję, która zwróci n największych wartości z zadanej macierzy.

In [63]:
def n_max(m,n):
    m=m.flatten()
    return m[np.argsort(m)[::-1][:n]]
print(n_max(np.array([[1,2,6,7],[10,8,9,3]]),4))
def n_max2(m,n):
    return np.sort(m,axis=None)[n:][::-1]

print(n_max2(np.array([[1,2,6,7],[10,8,9,3]]),4))

[10  9  8  7]
[10  9  8  7]


# Zadanie 8
Napisz funkcję, która zwróci najczęściej powtarzający się element macierzy.

In [96]:
def occurs(m):
    m=m.flatten()
    return "Najczęściej powtarzający sie element to: "+str(np.argmax(np.bincount(m)))
occurs(np.array([[2,2,3,4],[3,2,5,2]]))

'Najczęściej powtarzający sie element to: 2'

# Zadanie 9
Napisz funkcję, która dla zadanej macierzy 2d zwróci wiersze z unikalnymi (niepowtarzającymi się) wartośćiami.

In [98]:
def unique(m):
    return np.unique(m)
unique(np.array([[1,2,2],[2,5,5],[6,7,7],[9,8,6],[9,6,5]]))

array([1, 2, 5, 6, 7, 8, 9])

# Zadanie 10
Napisz funkcję, która obliczy odległość (np. euklidesową) dwóch punktów  P1  i  P2  w  Rn .

In [105]:
def euclidean_distance(a,b):
    return np.linalg.norm(a-b)
print(euclidean_distance(np.array([1,2]),np.array([3,2])))

def euclidean_distance2(a,b):
    return np.sum(np.abs(a-b)**2)**1/2
print(euclidean_distance2(np.array([1,2]),np.array([3,2])))

2.0
2.0


# Zadanie 11
Napisz funkcję, która sprawdzi czy podana macierz X o rozmiarze 2x2 jest rozwiązaniem równania macierzowego  aX^2+bX+c=0 , gdzie  a,b,c  to zadane macierze.

In [155]:
def solve(a,b,c,X):
    eq=a@np.linalg.matrix_power(X,2)+b@X+c
    if np.array_equal(eq,np.zeros((2,2))):
        return "Macierz X jest rozwiązaniem"
    else:
        return "Macierz X nie jest rozwiązaniem"
    
solve(np.array([[1,1],[1,1]]),np.array([[5,5],[5,5]]),np.array([[6,6],[6,6]]),np.array([[-1,-1],[-1,-1]]))

'Macierz X jest rozwiązaniem'

# Zadanie 12
Napisz funkcję, która obliczy n-tą liczbę Fibonacciego wykorzystując potęgowanie macierzy [[1,1],[1,0]] (https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego#Macierze_liczb_Fibonacciego).

In [141]:
def Fibonacci(n):
    f=np.array([[1,1],[1,0]])
    f=np.linalg.matrix_power(f, 5)
    return str(n)+" liczba Fibonacciego to " +str(f[0,1])
Fibonacci(5)

'5 liczba Fibonacciego to 5'

# Zadanie 13
Napisz funkcję, która obliczy n-tą liczbę Fibonacciego wykorzystując wzór Bineta (https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego#Wz%C3%B3r_Bineta).

In [25]:
import math

def Fibonacci_Binet(n):
    x=1/math.sqrt(5)*((1+math.sqrt(5))/2)**n-(1/math.sqrt(5))*((1-math.sqrt(5))/2)**n
    return x
                                                                    
Fibonacci_Binet(5)                                                                    

5.000000000000001

# Zadanie 14
Napisz funkcję, która wygeneruje macierz o losowych elementach (liczby całkowite z zadanego zakresu) o zadanej z góry wartości śladu macierzy (ang. trace).

In [51]:
def matrix(a,b,t):
    m=np.random.randint(a,b,(2,2))
    while np.trace(m)!=t:
        m=np.random.randint(a,b,(2,2))
    return m

matrix(0,2,2)

array([[1, 0],
       [0, 1]])